- name: Install Elasticsearch
  hosts: elasticsearch
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: "6.5.1"
    es_instance_name: "node1"
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      node.name: "node1"
      cluster.name: "blockmed"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: true
      network.host: 0.0.0.0
      discovery.zen.minimum_master_nodes: 1
    es_heap_size: 1g
    es_api_port: 9200
    es_xpack_features: ["monitoring"]
# Need to manual run search-guard initial tools at `<ES dir>/plugins/search-guard-6/tools/install_demo_configuration.sh` 
# and make sure the `*.pem` files stored in ES_CONFIG path `/etc/elasticsearch/node1/`
